extends: "default"

yaml-files:
  - '*.md'

rules:
    document-start:
        present: true
    braces:
        forbid: true
    brackets:
        forbid: true
    empty-values:
        forbid-in-block-mappings: true
        forbid-in-flow-mappings: true
    indentation:
        spaces: 4
        indent-sequences: false
    line-length: false
    quoted-strings:
        quote-type: "double"
        required: true
    comments:
        # Optional workflow parts
        require-starting-space: false
