name: Test

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

    workflow_dispatch:

jobs:
    lint_sass:
        name: Lint Sass
        runs-on: ubuntu-latest

        steps:
        -
            name: Checkout repository
            uses: actions/checkout@v3
        -
            name: Set up Node.js
            uses: actions/setup-node@v3
            with:
            node-version: 'lts/*'
        -
            name: Install dependencies
            run: npm ci
        -
            name: Run linter
            run: npm run sass:lint

    lint_all:
        name: Lint
        runs-on: ubuntu-latest

        steps:
        -
            name: Checkout repository
            uses: actions/checkout@v3
        -
            name: Cache pip
            uses: actions/cache@v3
            with:
            path: '~/.cache/pip'
            key: '${{ runner.os }}-pip-yamllint'
        -
            name: Install yamllint
            run: pip install --user yamllint
        -
            name: Check YAML formatting
            run: python -m yamllint ./
        -
            name: Check EditorConfig configuration
            run: test -f .editorconfig
        -
            name: Check adherence to EditorConfig
            uses: greut/eclint-action@v0
            with:
                eclint_args: |
                    -exclude=css/*
